apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo-namespace
  labels:
    app: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 372858676531.dkr.ecr.eu-north-1.amazonaws.com/enterprise-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
          
          envFrom:
          - configMapRef:
              name: backend-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20     

